### ISSUE TITLE
Windows - Not sure 

### ISSUE THREAD

**Issue by johners97** [openaps/decocare#24]
Using Windows. Looked at fuser.py and found is there a windows version of a fuser -k <  > folder

**Comment by johners97** [comment]
``C:\Python27>python decocare/decocare/stick.py COM4
INFO:__main__:howdy! I'm going to take a look at your carelink usb stick.
Traceback (most recent call last):
  File "decocare/decocare/stick.py", line 911, in <module>
    stick = Stick(link.Link(port))
  File "C:\Python27\decocare\decocare\link.py", line 22, in __init__
    if fuser.in_use(port):
  File "C:\Python27\decocare\decocare\fuser.py", line 11, in in_use
    pipe = Popen(['fuser', device], stdout=PIPE, stderr=PIPE)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified``
